### ISSUE TITLE
Management commands do not work with Django 1.7

### ISSUE THREAD

**Issue by hamole** [littleweaver/django-daguerre#67]
Running ./manage.py daguerre clean under Django 1.7 returns the error

```
ImportError: cannot import name find_management_module
```

Suspect it is the same issue as https://github.com/tomchristie/django-pdb/issues/20
